using Hearthstone.Services;
using Microsoft.AspNetCore.Mvc;
using Hearthstone.Services;
using Hearthstone.Models;
using MongoDB.Driver;


// For more information on enabling Web API for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Hearthstone.Controllers
{
    [Route("[controller]")]
    [ApiController]
    public class classesController : ControllerBase
    {
        private readonly HearthstoneService _hearthstoneService;
        private readonly ControllerLogger _logger = new ControllerLogger();
        public classesController(HearthstoneService hearthstoneService) =>
            _hearthstoneService = hearthstoneService;

        #region F4 classses
        //F4 An endpoint @ GET /classes that returns all available classes
        [HttpGet("/classes")]
        public async Task<ActionResult<List<Class>>> GetClasses()
        {
            //throw new NotImplementedException();
            _logger.OutputLine("GetClasses ran with Query: " + Request.QueryString);
            return await _hearthstoneService.Classes.Find(_ => true).ToListAsync();
        }
        #endregion



        //#region AutogeneratedEndpoints
        //// GET: api/<classesController>
        //[HttpGet]
        //public IEnumerable<string> Get()
        //{
        //    return new string[] { "value1", "value2" };
        //}

        //// GET api/<classesController>/5
        //[HttpGet("{id}")]
        //public string Get(int id)
        //{
        //    return "value";
        //}

        //// POST api/<classesController>
        //[HttpPost]
        //public void Post([FromBody] string value)
        //{
        //}

        //// PUT api/<classesController>/5
        //[HttpPut("{id}")]
        //public void Put(int id, [FromBody] string value)
        //{
        //}

        //// DELETE api/<classesController>/5
        //[HttpDelete("{id}")]
        //public void Delete(int id)
        //{
        //}
        //#endregion
    }
}
