using Hearthstone.Services;
using Microsoft.AspNetCore.Mvc;
using Hearthstone.Services;
using Hearthstone.Models;
using MongoDB.Driver;
// For more information on enabling Web API for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Hearthstone.Controllers
{
    [Route("[controller]")]
    [ApiController]
    public class raritiesController : ControllerBase
    {
        private readonly HearthstoneService _hearthstoneService;
        private readonly ControllerLogger _logger = new ControllerLogger();
        public raritiesController(HearthstoneService hearthstoneService) =>
            _hearthstoneService = hearthstoneService;

        #region F3 rarities
        //F3 An endpoint @ GET /rarities that returns all available rarities
        [HttpGet("/rarities")]
        public async Task<ActionResult<List<Rarity>>> GetRarities()
        {
            //throw new NotImplementedException();
            _logger.OutputLine("GetRarities ran with Query: " + Request.QueryString);
            return await _hearthstoneService.Rarities.Find(_ => true).ToListAsync();
        }
        #endregion


        //#region AutoGeneratedEndpoints
        //// GET: api/<raritiesController>
        //[HttpGet]
        //public IEnumerable<string> Get()
        //{
        //    return new string[] { "value1", "value2" };
        //}

        //// GET api/<raritiesController>/5
        //[HttpGet("{id}")]
        //public string Get(int id)
        //{
        //    return "value";
        //}

        //// POST api/<raritiesController>
        //[HttpPost]
        //public void Post([FromBody] string value)
        //{
        //}

        //// PUT api/<raritiesController>/5
        //[HttpPut("{id}")]
        //public void Put(int id, [FromBody] string value)
        //{
        //}

        //// DELETE api/<raritiesController>/5
        //[HttpDelete("{id}")]
        //public void Delete(int id)
        //{
        //}
        //#endregion
    }
}
