using Hearthstone.Services;
using Microsoft.AspNetCore.Mvc;
using Hearthstone.Services;
using Hearthstone.Models;
using MongoDB.Driver;
// For more information on enabling Web API for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Hearthstone.Controllers
{
    [Route("[controller]")]
    [ApiController]
    public class setsController : ControllerBase
    {
        private readonly HearthstoneService _hearthstoneService;
        public setsController(HearthstoneService hearthstoneService) =>
            _hearthstoneService = hearthstoneService;

        #region F2 sets
        //F2 An endpoint @ GET /sets that returns all available sets
        [HttpGet("/sets")]
        public async Task<ActionResult<List<Set>>> GetSets()
        {
            return await _hearthstoneService.Sets.Find(_ => true).ToListAsync();
        }

        #endregion
        //#region AutoGeneratedEndpoints
        //// GET: api/<setsController>
        //[HttpGet]
        //public IEnumerable<string> Get()
        //{
        //    return new string[] { "value1", "value2" };
        //}

        //// GET api/<setsController>/5
        //[HttpGet("{id}")]
        //public string Get(int id)
        //{
        //    return "value";
        //}

        //// POST api/<setsController>
        //[HttpPost]
        //public void Post([FromBody] string value)
        //{
        //}

        //// PUT api/<setsController>/5
        //[HttpPut("{id}")]
        //public void Put(int id, [FromBody] string value)
        //{
        //}

        //// DELETE api/<setsController>/5
        //[HttpDelete("{id}")]
        //public void Delete(int id)
        //{
        //}
        //#endregion
    }
}
