# Use root/example as user/password credentials
version: '3.9'
services:
  api:
    depends_on:
      - mongo
    image: "mathiasschjoedtbavngaard/sw4bed-01-handin-4-hearthstone:API_v6"
    ports:
     - 5011:80
    environment:
        - "Connectionstrings:default=mongodb://root:example@mongo:27017/" 
    # volumes:
    #   - .:/https:ro    
  mongo:
    image: mongo
    restart: always
    ports: 
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  # mongo-express:
  #   depends_on:
  #     - mongo
  #   image: mongo-express
  #   restart: always
  #   ports:  
  #     - 5050:8081
  #   environment:
  #     ME_CONFIG_BASICAUTH_USERNAME: user
  #     ME_CONFIG_BASICAUTH_PASSWORD: password
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #     # ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
  #     ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
